var annotated_dup =
[
    [ "__adsoutputstream", "struct____adsoutputstream.html", "struct____adsoutputstream" ],
    [ "_ads_formatInfo", "struct__ads__format_info.html", "struct__ads__format_info" ],
    [ "_ads_td", "struct__ads__td.html", "struct__ads__td" ],
    [ "_ads_time", "struct__ads__time.html", "struct__ads__time" ],
    [ "_baseNode", "struct__base_node.html", "struct__base_node" ],
    [ "_SDB", "struct___s_d_b.html", "struct___s_d_b" ],
    [ "_sdbMasterDB", "struct__sdb_master_d_b.html", "struct__sdb_master_d_b" ],
    [ "_sdbTable", "struct__sdb_table.html", "struct__sdb_table" ],
    [ "_staticDB", "struct__static_d_b.html", "struct__static_d_b" ],
    [ "_storeStruct", "struct__store_struct.html", "struct__store_struct" ],
    [ "_stringBase", "struct__string_base.html", "struct__string_base" ],
    [ "ads_avl", "structads__avl.html", null ],
    [ "ads_format_detail", "structads__format__detail.html", "structads__format__detail" ],
    [ "ads_list", "structads__list.html", null ],
    [ "ads_structiterator", "structads__structiterator.html", "structads__structiterator" ],
    [ "ads_treeLeaf", "structads__tree_leaf.html", null ],
    [ "ads_tuple", "structads__tuple.html", null ],
    [ "ads_vector", "structads__vector.html", null ],
    [ "db_tuple_var", "structdb__tuple__var.html", "structdb__tuple__var" ],
    [ "deque", "structdeque.html", null ],
    [ "dict", "structdict.html", null ],
    [ "heap", "structheap.html", null ],
    [ "proc", "structproc.html", "structproc" ],
    [ "queue", "structqueue.html", null ],
    [ "sdb_pair", "structsdb__pair.html", "structsdb__pair" ],
    [ "sdb_sig", "structsdb__sig.html", "structsdb__sig" ],
    [ "set", "structset.html", null ],
    [ "stack", "structstack.html", null ],
    [ "string", "structstring.html", null ],
    [ "struct_db_tuple", "structstruct__db__tuple.html", "structstruct__db__tuple" ],
    [ "tree", "structtree.html", null ]
];