var modules =
[
    [ "Avltree", "group___avltree.html", "group___avltree" ],
    [ "Deque", "group__deque.html", "group__deque" ],
    [ "Dict", "group__dict.html", "group__dict" ],
    [ "Heap", "group__heap.html", "group__heap" ],
    [ "List", "group__list.html", "group__list" ],
    [ "Queue", "group__queue.html", "group__queue" ],
    [ "Set", "group__set.html", "group__set" ],
    [ "Stack", "group__stack.html", "group__stack" ],
    [ "String", "group__string.html", "group__string" ],
    [ "Tree", "group__tree.html", "group__tree" ],
    [ "Tuple", "group__tuple.html", "group__tuple" ],
    [ "Input-Output", "group___input-_output.html", "group___input-_output" ],
    [ "Garbage-Collector", "group___garbage-_collector.html", "group___garbage-_collector" ],
    [ "Iterator", "group___iterator.html", "group___iterator" ],
    [ "Object", "group___object.html", "group___object" ],
    [ "Time-it", "group__time-it.html", "group__time-it" ],
    [ "Parsing", "group___parsing.html", "group___parsing" ],
    [ "Misc", "group___misc.html", "group___misc" ],
    [ "Repr-Printing", "group___repr-_printing.html", "group___repr-_printing" ],
    [ "Compare-Functions", "group___compare-_functions.html", "group___compare-_functions" ],
    [ "Hash-Functions", "group___hash-_functions.html", "group___hash-_functions" ],
    [ "Vector", "group__vector.html", "group__vector" ]
];